apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: kube-system
spec:
  interval: 5m
  releaseName: sealed-secrets
  chart:
    spec:
      chart: sealed-secrets
      version: 2.3.0
      sourceRef:
        name: bitnami
        kind: HelmRepository
  values:
    image:
      registry: quay.io
      repository: bitnami/sealed-secrets-controller
      tag: v0.18.0
