apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-prosody
spec:
  storageClassName: local-path
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /var/lib/databases/prosody
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - sserver
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-prosody
  namespace: prosody
spec:
  storageClassName: local-path
  volumeName: database-prosody
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
