apiVersion: v1
kind: PersistentVolume
metadata:
  name: photos-nextcloud
spec:
  storageClassName: longhorn
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /srv/smb/media/photos
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - sserver
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photos-nextcloud
  namespace: nextcloud
spec:
  storageClassName: longhorn
  volumeName: photos-nextcloud
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
