apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  interval: 5m
  releaseName: jellyfin
  chart:
    spec:
      chart: jellyfin
      version: 9.4.2
      sourceRef:
        name: k8s-at-home
        namespace: flux-system
        kind: HelmRepository
  values:
    image:
      repository: jellyfin/jellyfin
      tag: 10.8.1
    env:
      TZ: "Europe/London"
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        ingressClassName: "nginx"
        hosts:
          - host: jellyfin.ssene.ca
            paths:
              - path: /
        tls:
          - hosts:
              - jellyfin.ssene.ca
            secretName: jellyfin-tls-cert
    persistence:
      config:
        enabled: true
      cache:
        enabled: true
        accessMode: ReadWriteOnce
        size: 1Gi
      music:
        enabled: true
        readOnly: true
        existingClaim: music
      books:
        enabled: true
        readOnly: true
        existingClaim: books
      shows:
        enabled: true
        readOnly: true
        existingClaim: shows
      movies:
        enabled: true
        readOnly: true
        existingClaim: movies
      youtube:
        enabled: true
        existingClaim: youtube
    resources:
      requests:
        gpu.intel.com/i915: 1
      limits:
        gpu.intel.com/i915: 1
