apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-music
spec:
  storageClassName: local-path
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /srv/smb/media/music
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-music
  namespace: jellyfin
spec:
  storageClassName: local-path
  volumeName: jellyfin-music
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-podcasts
spec:
  storageClassName: local-path
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /srv/smb/media/podcasts
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-podcasts
  namespace: jellyfin
spec:
  storageClassName: local-path
  volumeName: jellyfin-podcasts
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-youtube
spec:
  storageClassName: local-path
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /srv/smb/media/youtube
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-youtube
  namespace: jellyfin
spec:
  storageClassName: local-path
  volumeName: jellyfin-youtube
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-lectures
spec:
  storageClassName: local-path
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /srv/smb/media/lectures
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-lectures
  namespace: jellyfin
spec:
  storageClassName: local-path
  volumeName: jellyfin-lectures
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-shows
spec:
  storageClassName: local-path
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /srv/smb/media/shows
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-shows
  namespace: jellyfin
spec:
  storageClassName: local-path
  volumeName: jellyfin-shows
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-books
spec:
  storageClassName: local-path
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /srv/smb/media/books
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-books
  namespace: jellyfin
spec:
  storageClassName: local-path
  volumeName: jellyfin-books
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-movies
spec:
  storageClassName: local-path
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /srv/smb/media/movies
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-movies
  namespace: jellyfin
spec:
  storageClassName: local-path
  volumeName: jellyfin-movies
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
